"""Initiate structure.

Revision ID: f68f9d3f8e53
Revises:
Create Date: 2024-04-24 12:41:53.419658+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f68f9d3f8e53"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prefixes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("parent_prefix_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.ForeignKeyConstraint(
            ["parent_prefix_id"],
            ["prefixes.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_codes",
        sa.Column("prefix_id", sa.Integer(), nullable=False),
        sa.Column("increment", sa.Integer(), nullable=False),
        sa.Column("custom_message", sa.String(), nullable=True),
        sa.Column("hint", sa.String(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "CRITICAL", "ERROR", "WARNING", "INFO", name="eventcodeseverityenum"
            ),
            nullable=False,
        ),
        sa.Column("dev_note", sa.String(), nullable=True),
        sa.Column("is_deprecated", sa.Boolean(), server_default="f", nullable=False),
        sa.Column(
            "use_generic_message", sa.Boolean(), server_default="f", nullable=False
        ),
        sa.Column("is_private", sa.Boolean(), server_default="f", nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique UUID identifier",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last update",
        ),
        sa.ForeignKeyConstraint(
            ["prefix_id"], ["prefixes.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_codes")
    sa.Enum(name="eventcodeseverityenum").drop(op.get_bind())
    op.drop_table("prefixes")
    # ### end Alembic commands ###
